export const AMANDEX_DEFAULTS = {
  img_1: "amanda1.png",
  text_1: "Sobre",
  text_2: "Diferenciais",
  text_3: "Procedimentos",
  text_4: "Consultório",
  text_5: "Resultados",
  text_6: "FAQ",
  text_7: "Agendar Avaliação",
  text_8: "Sobre",
  text_9: "Diferenciais",
  text_10: "Procedimentos",
  text_11: "Consultório",
  text_12: "Resultados",
  text_13: "FAQ",
  text_14: "Agendar",
  text_15: "Odontologia de Alto Padrão",
  text_16: "Sorrisos têm",
  text_17: "segunda chance.",
  img_2: "amanda2.png",
  text_18: "CRO-RJ 57092",
  text_19: "Cirurgiã-Dentista",
  text_20: "Iniciar Tratamento",
  img_3: "amanda7.png",
  text_21: "Sobre sua dentista",
  text_22: "Conheça a",
  text_23: "Dra. Amanda",
  text_24: "Dra. Amanda Araujo é cirurgiã-dentista com foco em estética e reabilitação oral, comprometida com resultados naturais e um atendimento sensível às necessidades de cada paciente.",
  text_25: "Formada em Odontologia, com atualização em Reabilitação Oral e Harmonização Orofacial, ela construiu seu próprio consultório em Campos dos Goytacazes, um espaço pensado para que cada paciente se sinta tratado de forma humana do início ao fim.",
  text_26: "Co-fundadora do Odonto360, evento de referência para dentistas na região, a Dra. Amanda acredita que o empreendedorismo é o caminho para uma odontologia mais livre, mais próspera e mais humana.",
  text_27: "Para ela, sorrisos têm segunda chance. E cada tratamento é uma oportunidade de provar isso.",
  text_28: "Por que me",
  text_29: "escolher?",
  text_30: "Atendimento Humanizado",
  text_31: "Cuidado genuíno com as pessoas. Aqui você é ouvido e tratado com total dedicação e empatia.",
  text_32: "Técnica e Atualização",
  text_33: "Formação contínua e dedicação para trazer sempre as técnicas mais modernas.",
  text_34: "Consultório Acolhedor",
  text_35: "Um espaço próprio pensado em cada detalhe para o seu conforto e relaxamento.",
  text_36: "Transparência",
  text_37: "Clareza em cada etapa do processo. Você sabe exatamente o que está sendo feito e por quê.",
  text_38: "Resultados que respeitam você",
  text_39: "Buscamos a harmonia perfeita, realçando sua beleza sem perder a sua essência natural.",
  text_40: "Procedimentos",
  text_41: "Tratamentos",
  text_42: "Avançados",
  img_4: "amanda-trat1.png",
  text_43: "Limpeza e Prevenção",
  text_44: "A limpeza profissional é o ponto de partida para uma boca saudável e para evitar tratamentos mais complexos no futuro. Simples, indolor e essencial.",
  img_5: "amanda-trat2.png",
  text_45: "Restauração",
  text_46: "Devolvemos a forma, a função e a estética do seu dente de forma natural e duradoura. Ninguém vai notar que foi restaurado, e é exatamente esse o objetivo.",
  img_6: "amanda-trat3.png",
  text_47: "Pino e Bloco/Coroa",
  text_48: "Quando o dente precisa de estrutura para ser reconstruído, usamos técnicas seguras e precisas para garantir que ele recupere sua função com força e naturalidade.",
  img_7: "amanda-trat4.png",
  text_49: "Facetas em Resina",
  text_50: "As facetas em resina corrigem cor, forma e imperfeições do sorriso, tudo em uma única sessão. Resultado imediato e natural para quem quer sorrir com mais confiança no dia a dia.",
  img_8: "amanda-trat5.png",
  text_51: "Facetas em Porcelana",
  text_52: "Para quem busca o mais alto padrão em estética dental. Reproduzindo a translucidez e o brilho natural dos dentes com uma durabilidade incomparável.",
  img_9: "amanda-trat6.png",
  text_53: "Próteses Dentárias",
  text_54: "Recupere sua mastigação, sua fala e o prazer de sorrir. As próteses são planejadas com cuidado para devolver função e estética, respeitando a sua anatomia e o seu rosto.",
  img_10: "amanda-trat7.png",
  text_55: "Placa para Bruxismo",
  text_56: "Se você range ou aperta os dentes, a placa miorrelaxante protege seus dentes do desgaste e alivia a tensão na musculatura. Um pequeno hábito que faz grande diferença.",
  img_11: "amanda-trat8.png",
  text_57: "HOF",
  text_58: "Toxina botulínica:",
  text_59: "Usada para prevenir e suavizar linhas de expressão que declaram o envelhecimento.",
  text_60: "Preenchimento Facial:",
  text_61: "Harmonizar e realçar o que há de melhor em você sem mudar quem você é.",
  text_62: "Nossos",
  text_63: "Especialistas",
  text_64: "O seu cuidado não para na minha cadeira. O consultório conta com uma equipe de especialistas de confiança para que você encontre tudo o que precisa em um só lugar, sem perder o acolhimento que é a nossa marca.",
  text_65: "Ortodontia",
  text_66: "Periodontia",
  text_67: "Cirurgia Bucomaxilofacial",
  text_68: "Fisioterapia (Bruxismo)",
  text_69: "Antes e Depois",
  text_70: "A arte de transformar",
  text_71: "sorrisos",
  img_12: "amanda12.png",
  text_72: "Antes",
  img_13: "amanda13.png",
  text_73: "Depois",
  img_14: "amanda20.png",
  text_74: "Antes",
  img_15: "amanda21.png",
  text_75: "Depois",
  img_16: "amanda22.png",
  text_76: "Antes",
  img_17: "amanda23.png",
  text_77: "Depois",
  img_18: "amanda24.png",
  text_78: "Antes",
  img_19: "amanda25.png",
  text_79: "Depois",
  img_20: "amanda26.png",
  text_80: "Antes",
  img_21: "amanda27.png",
  text_81: "Depois",
  text_82: "Arraste para comparar",
  text_83: "Depoimentos",
  text_84: "O que dizem nossos",
  text_85: "pacientes",
  text_86: "\"Amanda, está tão bonito… minha autoestima está melhor graças as suas mãos. Deus abençoe seu dom!!\"",
  text_87: "Jéssica de Oliveira Viana P. D'auriol",
  text_88: "Paciente",
  text_89: "\"Amanda é simplesmente sensacional! Uma profissional paciente, dedicada e gentil. Que sorte encontrá-la! 🥰🥰\"",
  text_90: "Ana Beatriz Verneque",
  text_91: "Paciente",
  text_92: "\"Um excelente acolhimento com atendimento profissional de ótima qualidade. Dra. Amanda Araujo, demonstrou eficiência e me proporcionou um tratamento muito humano. Obrigada.\"",
  text_93: "Vera Lucia Pimentel",
  text_94: "Paciente",
  text_95: "\"Obrigado mais uma vez, Amanda! Ficou ótimo! Sem falar no atendimento excelente.\"",
  text_96: "Marcio Brito",
  text_97: "Paciente",
  text_98: "Dúvidas Frequentes",
  text_99: "Perguntas",
  text_100: "Frequentes",
  text_101: "Atende convênios?",
  text_102: "No momento, o consultório não trabalha com convênios. Mas não deixe isso ser um obstáculo, oferecemos condições de pagamento facilitadas para que você cuide do seu sorriso sem preocupação.",
  text_103: "Como funciona o pagamento?",
  text_104: "Todos os procedimentos podem ser parcelados em até 12x no cartão de crédito. Após a sua consulta, apresentamos um plano de tratamento detalhado com os valores, para que você possa planejar com tranquilidade.",
  text_105: "Como faço para agendar uma consulta?",
  text_106: "Basta clicar no botão de WhatsApp aqui no site ou usar nossa Assistente Virtual no canto da tela. Nossa equipe vai te responder rapidinho e encontrar o melhor horário para você.",
  text_107: "Preciso sentir dor para ir ao dentista?",
  text_108: "Não! Essa é uma das ideias que mais nos preocupa. Consultas de rotina e limpezas regulares são exatamente o que evita que os problemas cheguem a dar dor. Quanto antes você vier, mais simples — e mais barato — é o tratamento.",
  text_109: "Quanto tempo dura uma consulta?",
  text_110: "Depende do procedimento. Uma consulta de avaliação com limpeza, por exemplo, dura em média 1 hora. Tratamentos mais complexos podem ser divididos em sessões para garantir conforto e qualidade. Tudo é planejado e comunicado com antecedência.",
  text_111: "O consultório atende casos de bruxismo?",
  text_112: "Sim, e com um diferencial importante: além do tratamento odontológico com placa miorrelaxante, contamos com uma fisioterapeuta especializada no atendimento de pacientes com bruxismo. Um cuidado completo, do dente ao músculo.",
  text_113: "O Consultório",
  text_114: "Conforto e",
  text_115: "Tecnologia",
  img_22: "amanda3.png",
  img_23: "amanda4.png",
  img_24: "amanda5.png",
  text_116: "Detalhes que fazem",
  text_117: "toda a diferença.",
  text_118: "Mais do que sorrisos,",
  text_119: "uma rotina de cuidados.",
  text_120: "Acompanhe dicas exclusivas, os bastidores do nosso consultório e inspire-se com mais resultados reais todos os dias no nosso Instagram.",
  img_25: "amanda-reel1.png",
  img_26: "amanda-reel2.png",
  img_27: "amanda-reel3.png",
  img_28: "amanda-reel4.png",
  text_121: "Acompanhar no Instagram",
  img_29: "amanda1.png",
  text_122: "Pronto para viver o seu",
  text_123: "melhor sorriso?",
  text_124: "Agende sua avaliação e descubra como a odontologia estética de alto padrão pode transformar sua confiança.",
  text_125: "Agendar pelo WhatsApp",
  text_126: "Localização Premium",
  text_127: "Ed. Alexander Fleming",
  text_128: "R. Conselheiro Otaviano, 84 - Centro",
  text_129: "Campos dos Goytacazes - RJ, 28010-140",
  text_130: "Atendimento com Hora Marcada",
  text_131: "Segunda a Sexta: 09h às 19h",
  text_132: "Sábados: 09h às 13h",
  text_133: "© 2026 Dra. Amanda Estética Dental.",
  text_134: "CRO-RJ 57092",
  text_135: "© 2026 DRA. AMANDA ESTÉTICA DENTAL",
  text_136: "CRIADO POR",
  text_137: "VERTICY.",
  text_138: "PREMIUM SITE",
};
