export const CRISTIANAPSI2_DEFAULTS = {
  img_1: "/assets/cristiana.psi2/cristiana_logo.png",
  img_2: "/assets/cristiana.psi2/cristiana_hero.png",
  text_1: "Cristiana",
  text_2: "Inafuku",
  text_3: "Psicóloga Clínica • CRP 06/229755",
  text_4: "Autoconhecimento",
  text_5: "Terapia Cognitivo-Comportamental",
  text_6: "Equilíbrio Emocional",
  text_7: "Autoconhecimento",
  text_8: "Ferramenta Interativa",
  text_9: "Como você está",
  text_10: "sentindo o agora?",
  text_11: "Reserve 30 segundos para uma breve autoanálise do seu estado atual.",
  text_12: "Começar Check-in",
  text_13: "Passo 1 de 3",
  text_14: "Você sente que sua mente \"não para\" mesmo em momentos de descanso?",
  text_15: "Sim, com frequência",
  text_16: "Às vezes",
  text_17: "Raramente",
  text_18: "Acolhimento Necessário",
  text_19: "Sua análise indica uma sobrecarga emocional. O diálogo é o primeiro passo para a sua liberdade mental.",
  text_20: "Agendar Conversa Clínica",
  img_3: "/assets/cristiana.psi2/cristiana_office.png",
  text_21: "A Essência",
  text_22: "da Mudança",
  text_23: "Minha missão é oferecer um ambiente seguro e humano para que você possa organizar o que se passa por dentro.",
  text_24: "Através da",
  text_25: "Terapia Cognitivo-Comportamental (TCC)",
  text_26: ", trabalhamos na construção de uma relação mais consciente e cuidadosa consigo mesma.",
  text_27: "Terapia Online",
  text_28: "Adultos",
  text_29: "Adolescentes",
  text_30: "O Diferencial do",
  text_31: "Atendimento Online",
  text_32: "Comodidade",
  text_33: "No seu espaço seguro.",
  text_34: "Flexibilidade",
  text_35: "Horários sob medida.",
  text_36: "Continuidade",
  text_37: "Tratamento sem fronteiras.",
  text_38: "\"A maneira como pensamos influencia diretamente como nos sentimos",
  text_39: "— e agimos.\"",
  text_40: "Aaron Beck • Pai da TCC",
  text_41: "Vamos reconstruir sua",
  text_42: "Saúde Mental?",
  text_43: "Agendar Atendimento",
  text_44: "@crisinafuku.psi",
  text_45: "© 2026 CRISTIANA INAFUKU • PSICOLOGIA",
  text_46: "CRIADO POR",
  text_47: "VERTICY.",
  text_48: "PREMIUM BIO",
};
