export const DAYFORADOAR_DEFAULTS = {
  text_1: "Preparando um sorriso lindo...",
  text_2: "Dra. Dayanne Jordão",
  text_3: "Odontopediatria",
  text_4: "Agendar Consulta",
  text_5: "Especialista em Bebês, Crianças e PNE",
  text_6: "Cuidar do sorriso do seu filho pode ser",
  text_7: "leve, tranquilo",
  text_8: "e até divertido ✨",
  img_1: "day1.png",
  text_9: "Sem traumas",
  text_10: "Muito carinho",
  text_11: "Atendimento odontopediátrico especializado com carinho, paciência e um ambiente pensado para encantar desde o primeiro dentinho.",
  text_12: "Agendar em Campos",
  text_13: "Agendar em Ipatinga",
  img_2: "day2.png",
  text_14: "Muito prazer, mamães e papais! 💖",
  text_15: "Sou a",
  text_16: "Dra. Dayanne Jordão",
  text_17: ", odontopediatra apaixonada por transformar a experiência das crianças no dentista.",
  text_18: "\"Minha missão é fazer com que cada consulta seja leve, acolhedora e sem medo — tanto para os pequenos quanto para os pais.\"",
  text_19: "Sou especialista, mestranda e professora na área de odontopediatria, e atuo com foco em um",
  text_20: "atendimento humanizado",
  text_21: ", respeitando o tempo e as necessidades de cada criança.",
  text_22: "Aqui, cada sorriso é cuidado com carinho, atenção e dedicação 💫",
  text_23: "Por que escolher nosso cantinho?",
  text_24: "Detalhes que fazem toda a diferença para o bem-estar do seu filho.",
  text_25: "Atendimento humanizado",
  text_26: "Cada criança é única e respeitada no seu tempo, com muita escuta e empatia.",
  text_27: "Ambiente lúdico",
  text_28: "Consultório preparado, colorido e divertido para acolher e encantar os pequenos.",
  text_29: "Especialista em bebês",
  text_30: "Cuidado especializado e orientações valiosas desde os primeiros meses de vida.",
  text_31: "Atendimento PNE",
  text_32: "Experiência, capacitação e estrutura para receber crianças com necessidades especiais.",
  text_33: "Técnicas sem trauma",
  text_34: "Abordagem psicológica leve, lúdica e focada em evitar qualquer tipo de medo.",
  text_35: "Quem nós cuidamos?",
  text_36: "Se você quer evitar traumas e cuidar da saúde bucal desde cedo, esse atendimento é ideal para o seu filho.",
  text_37: "Bebês",
  text_38: "Crianças",
  text_39: "Pacientes PNE",
  text_40: "Como funciona a nossa mágica? ✨",
  text_41: "Uma jornada simples, acolhedora e cheia de carinho.",
  text_42: "Primeiro contato",
  text_43: "Você envia uma mensagem e recebe orientações claras, rápidas e humanizadas da nossa equipe.",
  text_44: "Consulta acolhedora",
  text_45: "Um atendimento leve, lúdico, que respeita o tempo da criança e foca em construir confiança.",
  text_46: "Acompanhamento",
  text_47: "Cuidado contínuo e preventivo para garantir que a saúde bucal esteja sempre brilhando!",
  text_48: "Um ambiente pensado para transformar medo em confiança 💖",
  text_49: "Aqui, a criança se sente segura, acolhida e até se diverte durante o atendimento.",
  img_3: "day3.png",
  img_4: "day4.png",
  img_5: "day5.png",
  img_6: "day6.png",
  text_50: "Deslize para ver mais",
  text_51: "O que as mamães dizem",
  text_52: "Histórias reais de sorrisos transformados.",
  text_53: "\"Minha filha tinha muito medo de dentista, mas a paciência e a forma lúdica da Dra. Dayanne mudaram tudo. Hoje ela entra sorrindo e não quer ir embora!\"",
  text_54: "— Mãe da Sofia, 5 anos",
  text_55: "\"Atendimento incrível, muito carinho e paciência. Meu filho é autista e fomos acolhidos de uma forma maravilhosa. Indico de olhos fechados.\"",
  text_56: "— Mãe do Leo, 7 anos",
  text_57: "\"Profissional que realmente entende o universo das crianças! Trouxe meu bebê para a primeira consulta e recebi orientações valiosas. Tudo perfeito.\"",
  text_58: "— Mãe do Noah, 11 meses",
  text_59: "Pronta para transformar a consulta do seu filho? 🚀",
  text_60: "Seu filho merece um atendimento sem medo, com carinho e confiança 💫",
  text_61: "Agende agora e proporcione uma experiência positiva desde a infância.",
  text_62: "Campos dos Goytacazes",
  text_63: "Agendamento via WhatsApp",
  text_64: "(22) 99981-1131",
  text_65: "Falar com a recepção",
  text_66: "Ipatinga",
  text_67: "Agendamento via WhatsApp",
  text_68: "(31) 98830-7017",
  text_69: "Falar com a recepção",
  text_70: "Dra. Dayanne Jordão",
  text_71: "Odontopediatra | Bebês, Crianças e PNE",
  text_72: "\"Cuidando do sorriso com carinho desde os primeiros dentinhos 💖\"",
  text_73: "Dra. Dayanne Jordão. Todos os direitos reservados.",
};
