export const DRAANDREZZA_DEFAULTS = {
  text_1: "Preparando sorrisos com a Dra. Andrezza...",
  text_2: "Dra. Andrezza Barreto",
  text_3: "Odontopediatria • Campos/RJ",
  text_4: "Agendar",
  text_5: "Especialista em Atendimento Infantil",
  text_6: "Cuidado de especialista com o",
  text_7: "acolhimento de mãe",
  img_1: "/assets/dra.andrezza/andrezza1.png",
  text_8: "Mamãe do Alvin e da Anna Luiza, transformando a ida ao dentista em um momento de alegria e segurança para o seu filho.",
  text_9: "Agendar via WhatsApp",
  img_2: "/assets/dra.andrezza/andrezza2.png",
  text_10: "\"Quem me vê, me vê sorrindo.\"",
  text_11: "Quem sou eu? 💖",
  text_12: "Olá! Sou a",
  text_13: "Dra. Andrezza Barreto",
  text_14: ", mãe do Alvin e da Anna Luiza, apaixonada por cuidar de sorrisos.",
  text_15: "Com",
  text_16: "40 anos",
  text_17: "e muita determinação, busco unir a técnica odontológica ao carinho materno que toda criança merece.",
  img_3: "/assets/dra.andrezza/andrezza3.png",
  text_18: "\"Aqui no meu cantinho, cada detalhe é pensado para que seu filho saia com um sorriso brilhante!\"",
  text_19: "Amo café, chocolate e lugares frios, mas nada supera ver a evolução de cada pequeno paciente.",
  text_20: "Momentos Mágicos ✨",
  text_21: "Cada cuidado, uma história de confiança.",
  img_4: "/assets/dra.andrezza/andrezza4.png",
  text_22: "Sedação Consciente ☁️",
  img_5: "/assets/dra.andrezza/andrezza5.png",
  text_23: "BB Clínica 👶",
  img_6: "/assets/dra.andrezza/andrezza6.png",
  text_24: "Ambiente Lúdico 🎨",
  text_25: "Agenda Aberta em Campos! ✨",
  text_26: "Clique abaixo para garantir o melhor horário para o seu filho.",
  text_27: "Agendar Agora",
  text_28: "(22) 99848-8121",
  text_29: "Dra. Andrezza Barreto",
  text_30: "Dra. Andrezza Barreto • Campos/RJ",
};
