export const DRARAISABASTOS_DEFAULTS = {
  text_1: "A preparar um mundo de sorrisos...",
  text_2: "Dra. Raísa Bastos",
  text_3: "Odontopediatria • CRO 43104",
  text_4: "Sobre",
  text_5: "Momentos",
  text_6: "Especialidades",
  text_7: "O Consultório",
  text_8: "Marcar Consulta",
  text_9: "✨ O Sorriso do seu filho em boas mãos",
  text_10: "Onde o cuidado vira",
  text_11: "brincadeira",
  text_12: "e diversão!",
  text_13: "Especialista em criar experiências positivas. Atendimento com",
  text_14: "Laserterapia",
  text_15: "para garantir zero dor e muita alegria para os pequenos.",
  text_16: "Agendar via WhatsApp",
  img_1: "raisa_hero.png",
  img_2: "raisa_perfil.png",
  text_17: "Muito prazer, sou a Raísa! 💖",
  text_18: "Sou a",
  text_19: "Dra. Raísa Bastos",
  text_20: ", odontopediatra que acredita que o consultório deve ser um lugar de luz, cores e muitos sorrisos sinceros.",
  text_21: "Com especialização em",
  text_22: "Odontopediatria e Laserterapia",
  text_23: ", dedico-me a tratamentos humanizados para bebés, crianças e adolescentes, com um carinho especial por pacientes PNE.",
  text_24: "\"O meu superpoder? É a paciência e a alegria. Transformo o medo em coragem e cada consulta numa grande aventura lúdica!\"",
  text_25: "Sorrisos que nos movem ✨",
  text_26: "As crianças adoram o nosso cantinho porque aqui a alegria e a diversão são as regras principais!",
  img_3: "paciente1.png",
  text_27: "Felicidade em cada detalhe!",
  img_4: "paciente2.png",
  text_28: "Brincar ajuda a cuidar.",
  img_5: "paciente3.png",
  text_29: "Paciência infinita 💖",
  img_6: "paciente4.png",
  text_30: "Coragem que brilha!",
  text_31: "Deslize para ver mais momentos mágicos",
  text_32: "Laserterapia",
  text_33: "Tratamentos rápidos e sem dor para aftas, herpes e cicatrização. Tecnologia que garante o máximo conforto.",
  text_34: "Atendimento PNE",
  text_35: "Acolhimento especializado para pacientes com necessidades especiais, com foco total na calma e bem-estar.",
  text_36: "Odonto para Bebês",
  text_37: "Prevenção e acompanhamento lúdico desde o nascimento até os primeiros dentinhos. O cuidado começa cedo!",
  text_38: "Um mundo de cores 🎨",
  text_39: "Conheça o nosso espaço lúdico preparado para acolher a sua família.",
  img_7: "consultorio1.png",
  img_8: "consultorio2.png",
  img_9: "consultorio3.png",
  text_40: "Vamos agendar um sorriso saudável? 🚀",
  text_41: "Onde estamos",
  text_42: "Edifício Pelinca Prime, Sala 711",
  text_43: "Campos dos Goytacazes/RJ",
  text_44: "Contato Direto",
  text_45: "(22) 99936-9695",
  text_46: "raisabastoss1@gmail.com",
  text_47: "Agendar Agora",
  text_48: "Dra. Raísa Bastos © 2026 • CRO 43104",
  text_49: "Desenvolvido com carinho para pequenos sorrisos.",
};
