export const DUDU_DEFAULTS = {
  text_1: "Food Service",
  text_2: "Eduardo Bastos",
  text_3: "@dudubastos.delivery",
  text_4: "Gestão de Restaurantes na",
  text_5: "PRÁTICA",
  text_6: ". Te mostro a realidade de ser dono de restaurante sem mentiras. 🍔🍕",
  text_7: "+240 Mil",
  text_8: "Pedidos / Ano",
  text_9: "+71 Mil",
  text_10: "Seguidores",
  text_11: "Meus Links",
  text_12: "Mentoria de Gestão",
  text_13: "Acelere seu restaurante",
  text_14: "Consultoria Individual",
  text_15: "Análise do seu negócio",
  text_16: "Comunidade VIP",
  text_17: "Networking para Donos",
  text_18: "Na Prática",
  text_19: "A realidade sem filtros da cozinha.",
  text_20: "Ver Reels",
  text_21: "Montando burguer em 30 Segundos",
  text_22: "Operação",
  text_23: "Metas pra aumentar salário da equipe",
  text_24: "Gestão",
  text_25: "1000 Burguers hoje nessa cozinha",
  text_26: "Escala",
  text_27: "Entre em contato",
  text_28: "© 2026 EDUARDO BASTOS",
  text_29: "CRIADO POR",
  text_30: "VERTICY.",
  text_31: "PREMIUM BIO",
};
