export const GABI1_DEFAULTS = {
  img_1: "/assets/gabi1/gabi1.png",
  text_1: "Maternidade Real",
  text_2: "@gabimouraos",
  text_3: "Gabriella",
  text_4: "Mourão",
  text_5: "Eu sou a",
  text_6: "Gabi",
  text_7: ", tenho",
  text_8: "30 anos",
  text_9: ", ruiva natural, casada, mãe de",
  text_10: "dois filhos e um cachorro",
  text_11: "Levo a vida de forma leve, acreditando que a",
  text_12: "maternidade não precisa apagar a mulher",
  text_13: "e eu mostro todos os dias como é possível cuidar de um filho com amor, dividir responsabilidades e ainda não se perder de você mesma.",
  text_14: "Impacto Digital",
  text_15: "Visualizações (Reels)",
  text_16: "36.3M",
  text_17: "23.4K",
  text_18: "Seguidores",
  text_19: "15.7M",
  text_20: "Alcance",
  text_21: "3.1M",
  text_22: "Interações",
  text_23: "10M",
  text_24: "Views TikTok",
  text_25: "866K",
  text_26: "Curtidas (TT)",
  text_27: "Top Viral Reel",
  text_28: "21.2M",
  text_29: "\"A babá do meu filho vive um relacionamento tóxico\"",
  text_30: "Meus Cupons",
  text_31: "Kérastase",
  text_32: "Benefício Exclusivo",
  text_33: "Use o código:",
  text_34: "KERASTASESTARS",
  text_35: "Garanta",
  text_36: "10% OFF",
  text_37: "+ Brindes e Minis",
  text_38: "O Caos",
  text_39: "A Beleza",
  text_40: "A Maternidade como ela é",
  img_2: "/assets/gabi1/gabi2.png",
  text_41: "Maternidade",
  text_42: "Sem filtros",
  img_3: "/assets/gabi1/gabi3.png",
  text_43: "Autocuidado",
  text_44: "Lifestyle",
  text_45: "Beleza",
  img_4: "/assets/gabi1/gabi4.png",
  text_46: "Família",
  text_47: "A nossa rotina",
  text_48: "Fale Comigo",
  text_49: "Parcerias e Trabalhos",
  text_50: "Enviar E-mail",
  text_51: "@gabimouraos",
  text_52: "© 2026 GABRIELLA MOURÃO",
  text_53: "CRIADO POR",
  text_54: "VERTICY.",
  text_55: "PREMIUM BIO",
};
