export const ILGNER_DEFAULTS = {
  text_1: "Evolução de Elite",
  img_1: "/assets/ilgner/Icn1.png",
  img_2: "/assets/ilgner/icn_logo.png",
  text_2: "Referência em Alta Performance",
  text_3: "ESTRATÉGIA +",
  text_4: "CONSISTÊNCIA",
  text_5: "Ilgner",
  text_6: "Chagas",
  text_7: "Referência absoluta em",
  text_8: "Alta Performance",
  text_9: "Fisiculturismo",
  text_10: ", Ilgner Chagas é a mente estratégica por trás de grandes transformações no cenário nacional.",
  text_11: "Com um histórico de",
  text_12: "inúmeras vitórias",
  text_13: "em competições de elite, liderando atletas nos cenários masculino e feminino ao topo do pódio através de uma metodologia de precisão técnica.",
  text_14: "\"A tua transformação é uma ciência exata.\" 🏆",
  text_15: "Vitórias Masculino",
  text_16: "Alta Performance",
  text_17: "Fisiculturismo Feminino",
  text_18: "Padrão ICNTEAM",
  text_19: "Vitórias Masculino",
  text_20: "Estratégia Pura",
  text_21: "PLANOS DE",
  text_22: "CONSULTORIA",
  text_23: "Entrega em até 3-5 dias úteis",
  text_24: "Plano Start",
  text_25: "O Início da Jornada",
  text_26: "Sem Revisão",
  text_27: "Plano individual completo",
  text_28: "Ajuste único gratuito em 30 dias",
  text_29: "Selecionar Plano",
  text_30: "Alta Performance",
  text_31: "Premium Plus",
  text_32: "Revisões Semanais",
  text_33: "Melhor ritmo de ajustes",
  text_34: "Resultados mais rápidos",
  text_35: "Assinar Premium",
  text_36: "Bimestral Premium",
  text_37: "Revisão Quinzenal",
  text_38: "Melhor custo x benefício",
  text_39: "Evolução contínua com economia",
  text_40: "Escolher Bimestral",
  text_41: "Trimestral Elite",
  text_42: "Plano Promocional",
  text_43: "Acompanhamento Total:",
  text_44: "Revisão semanal + Protocolo hormonal + Suplementação.",
  text_45: "Precisão Máxima:",
  text_46: "Ideal para transformação real até o verão com ajustes estratégicos.",
  text_47: "Acesso direto comigo, maior flexibilidade nos ajustes e suporte presente para garantir sua evolução.",
  text_48: "Garantir Vaga Promo",
  text_49: "Resultados",
  text_50: "ICNTEAM",
  text_51: "Histórico que prova o método",
  img_3: "/assets/ilgner/icn_res1.png",
  text_52: "Evolução",
  text_53: "Alta Performance",
  img_4: "/assets/ilgner/icn_res2.png",
  text_54: "Campeões",
  text_55: "Padrão ICN",
  text_56: "Inicie agora a sua",
  text_57: "Transformação",
  text_58: "Agendar Avaliação",
  text_59: "@icnteam",
  text_60: "© 2026 ICNTEAM - ILGNER CHAGAS",
  text_61: "CRIADO POR",
  text_62: "VERTICY.",
  text_63: "PREMIUM BIO",
};
