export const JT_DEFAULTS = {
  img_1: "jt1.png",
  text_1: "Sua máquina merece o melhor",
  text_2: "DESTRAVE",
  text_3: "SEU CORPO",
  text_4: "Agendar Avaliação",
  text_5: "O Especialista",
  text_6: "Dracma",
  text_7: "MGF",
  text_8: "Campos Atlético",
  text_9: "ETT",
  text_10: "Dracma",
  text_11: "MGF",
  text_12: "Campos Atlético",
  text_13: "ETT",
  img_2: "jt_especialista.png",
  text_14: "Jeferson",
  text_15: "Teixeira",
  text_16: "Criador do Método JT Performance",
  text_17: "Referência em recuperação muscular e otimização física, Jeferson desenvolveu uma técnica exclusiva que une a ciência da",
  text_18: "Quiropraxia",
  text_19: "à precisão da",
  text_20: "Liberação Miofascial",
  text_21: "Sente que seu corpo",
  text_22: "travou?",
  text_23: "Dores Recorrentes",
  text_24: "Tensões musculares que prejudicam o seu treino e o seu dia a dia.",
  text_25: "Cansaço Crônico",
  text_26: "Sensação de peso e fadiga, mesmo após períodos de descanso.",
  text_27: "\"Deixa eu te fazer uma conta rápida\"",
  text_28: "Upgrade de",
  text_29: "Saúde",
  text_30: "Plano Mensal JT Performance",
  text_31: "Padrão Elite",
  text_32: "Acompanhamento contínuo para manter sua máquina funcionando no auge.",
  text_33: "Consulte planos personalizados",
  text_34: "Ser um Aluno Jeferson Teixeira",
  text_35: "Elite",
  text_36: "JT Team",
  text_37: "Autoridade reconhecida por referências",
  img_3: "jt3.png",
  text_38: "Recuperação Máxima",
  text_39: "Bodybuilding",
  img_4: "jt4.png",
  text_40: "Mobilidade",
  text_41: "Superação",
  text_42: "Performance Elite",
  img_5: "jt5.png",
  text_43: "Resistência Muscular",
  text_44: "Running",
  text_45: "Feedbacks",
  text_46: "Provas Reais",
  text_47: "Toque para ver os depoimentos",
  img_6: "jt7.png",
  img_7: "jt8.png",
  img_8: "jt9.png",
  text_48: "Ver no perfil oficial",
  img_9: "jt6.png",
  text_49: "Mundo",
  text_50: "Corporativo",
  text_51: "Otimize a produtividade do seu time. Oferecemos soluções para fadiga muscular e dores posturais no ambiente de trabalho.",
  text_52: "Orçamento para Empresas",
  text_53: "Localização",
  text_54: "Campos dos Goytacazes - RJ",
  text_55: "Espaço Teixeira Terapia",
  text_56: "Rua Conselheiro Otaviano, 84 - Centro",
  text_57: "Maps",
  text_58: "Waze",
  text_59: "Upgrade de",
  text_60: "Performance",
  text_61: "Agendar Agora",
  text_62: "@jefersonteixeiraett",
  text_63: "© 2026 JEFERSON TEIXEIRA",
  text_64: "CRIADO POR",
  text_65: "VERTICY.",
  text_66: "PREMIUM BIO",
};
