export const LAVINIAPSI_DEFAULTS = {
  img_1: "/assets/lavinia.psi/lavinia1.png",
  text_1: "Lavínia",
  text_2: "Morais",
  text_3: "Psicóloga Clínica",
  text_4: "Iniciar Atendimento",
  text_5: "Escuta",
  text_6: "Acolhimento",
  text_7: "Transformação",
  text_8: "Escuta",
  text_9: "Acolhimento",
  text_10: "Autoanálise",
  text_11: "Termômetro de",
  text_12: "Bem-Estar",
  text_13: "Mapeie o seu estado emocional agora. Responda em 1 minuto e veja o seu indicador.",
  text_14: "\"O primeiro passo para o cuidado é a percepção do próprio estado.\"",
  text_15: "Analisar meu Momento Atual",
  text_16: "Questão 1 de 5",
  text_17: "Você tem sentido dificuldade em relaxar ou descansar a mente?",
  text_18: "Quase nunca",
  text_19: "Algumas vezes",
  text_20: "Frequentemente",
  text_21: "Quase todo o tempo",
  text_22: "Nível de Estresse: Alerta",
  text_23: "Notei que você está passando por um momento de alta carga emocional. É importante dar o próximo passo para o seu cuidado.",
  text_24: "Agendar Triagem de Acolhimento",
  text_25: "Inicie sua jornada de cuidado com foco total.",
  text_26: "O Cuidado",
  text_27: "Um espaço para o",
  text_28: "seu sentir.",
  text_29: "Nesse espaço, busco oferecer um encontro genuíno com a sua própria essência.",
  text_30: "Através da abordagem",
  text_31: "fenomenológica existencial",
  text_32: ", caminhamos juntos para compreender os caminhos para a sua saúde emocional.",
  text_33: "Trajetória Profissional",
  text_34: "Especialidades",
  text_35: "Atuação",
  text_36: "Foco Terapêutico",
  text_37: "Sexualidade Humana",
  text_38: "Terapia Sistêmica",
  text_39: "Localização",
  text_40: "Clínica Fata",
  text_41: "Medicina Plástica.",
  text_42: "Voluntariado",
  text_43: "Inst. Tonelia",
  text_44: "Suporte Oncológico.",
  text_45: "Psicoterapia",
  text_46: "Modalidades",
  text_47: "On-line",
  text_48: "Acolhimento sem fronteiras, no conforto do seu lar.",
  text_49: "Presencial",
  text_50: "Consultório localizado em Campos/RJ.",
  text_51: "Contato Direto",
  text_52: "Será um prazer te receber nesse processo.",
  text_53: "Agendar Atendimento",
  text_54: "@laviniamorais.psi",
  text_55: "© 2026 DRA. LAVÍNIA MORAIS •",
  text_56: "VERTICY.",
};
