export const LOYOLA_DEFAULTS = {
  text_1: "Parceiro Credenciado Caixa",
  text_2: "Thiago Loyola",
  text_3: "Consultor Imobiliário",
  text_4: "Ajudo famílias a conquistarem o sonho da casa própria com",
  text_5: "segurança, inteligência financeira e as melhores oportunidades",
  text_6: "do mercado.",
  text_7: "Falar com o Thiago",
  text_8: "Resposta rápida e atendimento exclusivo.",
  text_9: "Quem é Thiago Loyola?",
  text_10: "Empreendedor e especialista no mercado imobiliário, atuo com foco em trazer as melhores oportunidades de investimento e moradia para os meus clientes.",
  text_11: "À frente da",
  text_12: "Imobiliária Loyola",
  text_13: ", construí uma trajetória pautada na transparência, segurança e resultados. Minha missão é simplificar processos complexos, como os leilões e financiamentos.",
  text_14: "Minhas Especialidades",
  text_15: "Imóveis de Leilão",
  text_16: "Oportunidades únicas com alto desconto. Assessoria completa da arrematação até a posse desocupada.",
  text_17: "Financiamento",
  text_18: "FGTS",
  text_19: "Processo ágil pela Caixa.",
  text_20: "Lançamentos",
  text_21: "Loteamentos",
  text_22: "As melhores localizações.",
  text_23: "Proprietário",
  text_24: "Imobiliária",
  text_25: "Loyola",
  text_26: "@imobiliarialoyola",
  text_27: "Sonhos",
  text_28: "Realizados",
  text_29: "Famílias de casa nova",
  text_30: "Chave na Mão",
  text_31: "Mais uma família conquistando o seu imóvel próprio com segurança.",
  text_32: "Imóvel de Leilão",
  text_33: "Oportunidade incrível arrematada e entregue com sucesso.",
  text_34: "Novo Lar",
  text_35: "A alegria indescritível de entrar pela primeira vez na casa nova.",
  text_36: "Aprenda sobre",
  text_37: "o mercado",
  text_38: "Dicas Práticas",
  text_39: "Leilões",
  text_40: "Tomando posse de um imóvel desocupado.",
  text_41: "Financiamento",
  text_42: "Como quitar seu financiamento na metade do tempo.",
  text_43: "Resultados",
  text_44: "Relato de quem já comprou de leilão.",
  text_45: "Dúvidas Frequentes",
  text_46: "Comprar em leilão é seguro?",
  text_47: "Sim, é totalmente seguro quando feito com assessoria especializada. Cuidamos de toda a análise jurídica e documental para garantir que o seu investimento não tenha riscos.",
  text_48: "Posso usar o meu FGTS?",
  text_49: "Na grande maioria dos casos de venda direta e financiamentos pela Caixa, sim! O seu FGTS pode ser usado como entrada ou para abater o saldo devedor.",
  text_50: "E se o imóvel de leilão estiver ocupado?",
  text_51: "Nossa equipe atua ativamente na desocupação. Na maioria das vezes, resolvemos de forma amigável extrajudicialmente, garantindo a sua posse o mais rápido possível.",
  text_52: "© 2026 THIAGO LOYOLA IMÓVEIS",
  text_53: "CRIADO POR",
  text_54: "VERTICY.",
  text_55: "PREMIUM BIO",
};
