export const MANUEL_DEFAULTS = {
  text_1: "Performance",
  text_2: "Longevidade",
  img_1: "/assets/manuel/manuel1.png",
  text_3: "Manuel Lema",
  text_4: "@manuel.personal",
  text_5: "Especialista em hipertrofia e emagrecimento",
  text_6: "30+",
  text_7: "Dicas, memes e a rotina de quem faz acontecer!",
  text_8: "Agendar Avaliação",
  text_9: "Conhecer o Manuel",
  text_10: "+ 1000",
  text_11: "Vidas Mudadas",
  text_12: "60.1K",
  text_13: "Seguidores",
  text_14: "Hipertrofia",
  text_15: "Emagrecimento 30+",
  text_16: "Humor",
  text_17: "Memes",
  text_18: "Hipertrofia",
  text_19: "Emagrecimento 30+",
  text_20: "Humor",
  text_21: "Memes",
  text_22: "O Meu Conteúdo",
  img_2: "/assets/manuel/manuel2.png",
  text_23: "Técnica de Treino",
  img_3: "/assets/manuel/manuel3.png",
  text_24: "A Realidade",
  img_4: "/assets/manuel/manuel4.png",
  text_25: "Lifestyle",
  text_26: "Viagens",
  img_5: "/assets/manuel/manuel5.png",
  text_27: "Quem é o Manuel?",
  text_28: "Alta Performance",
  text_29: "Conexão",
  text_30: "Sou apaixonado por transformar a vida de pessoas acima dos 30 anos. Acredito firmemente que o processo de mudança física não tem de ser um castigo ou algo sem vida.",
  text_31: "Aqui encontras a ciência do treino aliada a uma",
  text_32: "boa dose de humor",
  text_33: "e realidade. O meu objetivo é mostrar-te como blindar a tua saúde e conquistar o corpo que desejas, sem deixares de viver a vida! ⚡",
  text_34: "Porquê focar nos",
  text_35: "30+?",
  text_36: "A partir dos 30, o metabolismo e a recuperação mudam. O treino genérico já não serve. A minha metodologia é desenhada para construir músculos e queimar gordura protegendo as tuas articulações.",
  text_37: "Pronto para",
  text_38: "evolução?",
  text_39: "Garantir a minha vaga",
  text_40: "@manuel.personal",
  text_41: "© 2026 MANUEL LEMA | CRIADO POR",
  text_42: "VERTICY.",
};
