export const TAISTORYMAKER_DEFAULTS = {
  img_1: "/assets/tai.storymaker/tai_capa.png",
  img_2: "/assets/tai.storymaker/tai_logo.png",
  text_1: "Storymaker",
  text_2: "Videomaker",
  text_3: "Você vive o momento.",
  text_4: "Eu crio a narrativa.",
  text_5: "Cobertura estratégica em tempo real para casamentos, marcas e eventos de alto padrão.",
  text_6: "Solicitar Orçamento",
  text_7: "\"Stories bem feitos não são detalhe.",
  text_8: "São decisão estratégica.\"",
  text_9: "Eu não faço stories bonitos.",
  text_10: "Eu construo narrativas.",
  text_11: "Portfólio",
  text_12: "Eu atendo 3",
  text_13: "principais serviços",
  text_14: "Cobertura em",
  text_15: "Tempo Real",
  text_16: "A cobertura é feita diretamente nos stories do cliente, criando conexão com a audiência e gerando proximidade.",
  text_17: "Empresas:",
  text_18: "Mais chances de futuros negócios.",
  text_19: "Eventos Sociais:",
  text_20: "Eternizar a emoção do momento enquanto ele acontece.",
  text_21: "Produção de",
  text_22: "Conteúdo",
  text_23: "Para negócios que precisam estar presentes no digital de forma consistente. O objetivo é transformar a sua marca em referência com vídeos criativos.",
  text_24: "Recorrentes:",
  text_25: "Para quem quer constância.",
  text_26: "Avulsas:",
  text_27: "Para demandas pontuais.",
  text_28: "VideoMaker em",
  text_29: "Eventos",
  text_30: "Se não deseja cobertura em tempo real, mas quer um resumo profissional do seu evento. Faço a captação e entrego um vídeo bem editado com os melhores momentos.",
  text_31: "\"Uma lembrança única, pronta para ser compartilhada.\"",
  text_32: "Momentos",
  text_33: "Inesquecíveis",
  text_34: "Ideal para que tipos de evento?",
  img_3: "/assets/tai.storymaker/tai_wedding.png",
  text_35: "Casamentos",
  text_36: "Mini Weddings",
  text_37: "Intimidade",
  text_38: "Detalhe",
  img_4: "/assets/tai.storymaker/tai_corp.png",
  text_39: "Eventos",
  text_40: "Corporativos",
  text_41: "Lançamentos",
  text_42: "Marcas",
  img_5: "/assets/tai.storymaker/tai_party.png",
  text_43: "Formaturas",
  text_44: "Aniversários",
  text_45: "Celebração Real Time",
  text_46: "\"Ter alguém registrando em tempo real é permitir que",
  text_47: "você reviva aquilo que não conseguiu ver.\"",
  text_48: "Se é um destes serviços",
  text_49: "que procura...",
  text_50: "Vamos juntos contar a história do seu evento ou construir a presença da sua marca.",
  text_51: "Pedir Informações",
  text_52: "@tainarafernandes__",
  text_53: "Tai • Storymaker",
  text_54: "Desenvolvido por Verticy",
};
