export const YAVEH_DEFAULTS = {
  img_1: "/assets/yaveh/yaveh1.png",
  img_2: "/assets/yaveh/yaveh2.png",
  text_1: "Fisioterapia Pediátrica",
  text_2: "Desenvolvimento",
  text_3: "com",
  text_4: "Afeto",
  text_5: "Ciência",
  text_6: "Agendar Avaliação",
  text_7: "Conheça a Dra. Isabela",
  text_8: "Desenvolvimento Motor",
  text_9: "Neuroreabilitação",
  text_10: "Fisioterapia Respiratória",
  text_11: "Cuidado com Afeto",
  text_12: "Desenvolvimento Motor",
  text_13: "Neuroreabilitação",
  text_14: "Fisioterapia Respiratória",
  text_15: "Cuidado com Afeto",
  img_3: "/assets/yaveh/yaveh3.png",
  text_16: "Dra. Isabela Baierle",
  text_17: "Fisioterapeuta Pediátrica",
  text_18: "Acredito que",
  text_19: "cada criança carrega um potencial independente do diagnóstico",
  text_20: ". Meu método une a mais alta técnica científica com cuidado humanizado.",
  text_21: "Aqui, cada pequena conquista é celebrada, e o cuidado vai muito além da clínica.",
  text_22: "Nossos Cuidados",
  text_23: "Intervenção e Afeto",
  text_24: "Desenvolvimento Infantil",
  text_25: "Acompanhamento e estimulação precoce de 0 a 1 ano.",
  text_26: "Fisio Respiratória",
  text_27: "Alívio em crises para noites de sono tranquilas.",
  text_28: "Neuroreabilitação",
  text_29: "Maximizando a independência e funcionalidade de crianças atípicas.",
  text_30: "Ambiente Acolhedor",
  text_31: "Cada detalhe foi pensado para acolher e cuidar de quem mais importa.",
  img_4: "/assets/yaveh/yaveh4.png",
  text_32: "A Árvore",
  text_33: "Um lugar lúdico",
  img_5: "/assets/yaveh/yaveh5.png",
  text_34: "Estrutura",
  text_35: "Luz e Calma",
  text_36: "\"O cuidado não termina na sessão.\"",
  text_37: "Cuidar do seu filho com segurança começa com a orientação certa. Por aqui, compartilho conteúdos de um jeito leve, real e possível.",
  text_38: "Seguir @yaveh.fisioped",
  text_39: "Localização",
  text_40: "Toledo - PR",
  text_41: "Edifício Toledo",
  text_42: "Rua Dom Pedro II, 2117 - Sala 402",
  text_43: "Maps",
  text_44: "Waze",
  text_45: "Aguardamos por você!",
  text_46: "Agendar Consulta",
  text_47: "© 2026 YAVEH FISIOTERAPIA",
  text_48: "CRIADO POR",
  text_49: "VERTICY.",
  text_50: "PREMIUM BIO",
};
