export const YAVEH2_DEFAULTS = {
  img_1: "yaveh1.png",
  img_2: "yaveh2.png",
  text_1: "Fisioterapia Pediátrica",
  text_2: "Desenvolvimento",
  text_3: "com",
  text_4: "Afeto",
  text_5: "Ciência",
  text_6: "Agendar Avaliação",
  text_7: "Conheça a Dra. Isabela",
  text_8: "Desenvolvimento Motor",
  text_9: "Neuroreabilitação Bobath",
  text_10: "Fisio Respiratória RTA",
  text_11: "Cuidado com Afeto",
  text_12: "Desenvolvimento Motor",
  text_13: "Neuroreabilitação Bobath",
  text_14: "Fisio Respiratória RTA",
  text_15: "Cuidado com Afeto",
  img_3: "yaveh3.png",
  text_16: "Dra. Isabela Baierle",
  text_17: "Fisioterapeuta Pediátrica",
  text_18: "Trabalhar com crianças é, antes de tudo, um",
  text_19: "ato de amor",
  text_20: ". Cada pequeno paciente que chega até mim carrega um universo único de histórias, desafios e potencialidades.",
  text_21: "Meu compromisso vai muito além da técnica —",
  text_22: "ele nasce do coração",
  text_23: "e se fortalece na responsabilidade de oferecer um cuidado que acolhe, estimula e transforma.",
  text_24: "Nossos Cuidados",
  text_25: "Técnica e Afeto em cada detalhe",
  text_26: "Intervenção Precoce",
  text_27: "A fisioterapia na intervenção precoce é fundamental para promover o desenvolvimento saudável do bebê e da criança desde os primeiros meses de vida. Por meio de estímulos adequados, é possível prevenir atrasos motores, melhorar a respiração, favorecer a postura, coordenação e fortalecer habilidades essenciais. Quanto mais cedo a intervenção, maiores são as chances de potencializar o desenvolvimento neuropsicomotor e proporcionar mais qualidade de vida, sempre respeitando seu ritmo.",
  text_28: "Falar com a Especialista",
  text_29: "Fisioterapia Neurológica",
  text_30: "Conceito Bobath",
  text_31: "O Conceito Bobath é uma abordagem terapêutica utilizada na fisioterapia neurológica, especialmente na pediatria, que tem como objetivo estimular o desenvolvimento motor e funcional da criança. Por meio de manuseios específicos e estímulos adequados, busca-se facilitar movimentos mais organizados, melhorar o controle postural, promover a independência funcional e favorecer a participação da criança em suas atividades do dia a dia, respeitando sempre seu ritmo e potencial.",
  text_32: "Agendar Avaliação",
  text_33: "Fisioterapia Respiratória",
  text_34: "Método RTA",
  text_35: "Reequilíbrio Toracoabdominal é um método de terapia manual global que tem por objetivo incentivar a ventilação pulmonar e promover a remoção de secreções pulmonares e das vias aéreas superiores através da reorganização do sinergismo muscular respiratório. Essa reorganização possibilita a redução do esforço muscular ventilatório, melhora a ventilação e otimiza as atividades funcionais, trazendo conforto e noites de sono mais tranquilas.",
  text_36: "Falar com a Especialista",
  text_37: "Ambiente Acolhedor",
  text_38: "Cada detalhe foi pensado para acolher e cuidar de quem mais importa.",
  img_4: "yaveh4.png",
  text_39: "A Árvore",
  text_40: "Um lugar lúdico",
  img_5: "yaveh5.png",
  text_41: "Estrutura",
  text_42: "Luz e Calma",
  text_43: "\"O cuidado não termina na sessão.\"",
  text_44: "Cuidar do seu filho com segurança começa com a orientação certa. Por aqui, compartilho conteúdos de um jeito leve, real e possível.",
  text_45: "Seguir @yaveh.fisioped",
  text_46: "Localização e Contato",
  text_47: "Toledo - PR",
  text_48: "Edifício Toledo",
  text_49: "Rua Dom Pedro II, 2117 - Sala 402",
  text_50: "yavehfisioterapiainfantil@gmail.com",
  text_51: "Maps",
  text_52: "Waze",
  text_53: "Aguardamos por você!",
  text_54: "Agendar Consulta",
  text_55: "© 2026 YAVEH FISIOTERAPIA",
  text_56: "CRIADO POR",
  text_57: "VERTICY.",
  text_58: "PREMIUM BIO",
};
