export const ZISA_DEFAULTS = {
  text_1: "Coleção Boreal",
  text_2: "Infinitas Possibilidades",
  text_3: "Boreal",
  text_4: "Showroom Exclusivo",
  text_5: "Infinitas Possibilidades",
  text_6: "Boreal",
  text_7: "Showroom Exclusivo",
  text_8: "Infinitas Possibilidades",
  text_9: "Boreal",
  text_10: "Showroom Exclusivo",
  text_11: "Atendimento",
  text_12: "Comprar Online",
  text_13: "Showroom",
  text_14: "Agendar Visita",
  text_15: "Novidades",
  text_16: "Acompanhe os looks",
  text_17: "O Conceito",
  text_18: "Sobre a",
  text_19: "ZiSa",
  text_20: "Na",
  text_21: "ZiSa",
  text_22: ", acreditamos que a moda é uma escolha com infinitas possibilidades. O nosso foco é trazer peças que valorizem a sua essência e se adaptem ao seu estilo.",
  text_23: "A nova Coleção",
  text_24: "Boreal",
  text_25: "chega para mostrar a intensidade das cores num encontro inusitado, equilibrando a elegância da alfaiataria com a versatilidade de peças essenciais para qualquer ocasião.",
  text_26: "Nossas Peças",
  text_27: "Cada detalhe é cuidadosamente selecionado para garantir caimento perfeito, conforto absoluto e aquele toque fashion que amamos.",
  text_28: "Nosso Showroom",
  text_29: "Campos dos Goytacazes - RJ",
  text_30: "Parque São Caetano",
  text_31: "Campos dos Goytacazes, RJ",
  text_32: "Agende o seu horário pelo WhatsApp",
  text_33: "Dúvidas comuns",
  text_34: "Informações Importantes",
  text_35: "Como funciona o Showroom?",
  text_36: "O nosso showroom no Parque São Caetano funciona exclusivamente com",
  text_37: "hora marcada",
  text_38: ". Assim, conseguimos oferecer um atendimento 100% personalizado para te ajudar a escolher os melhores looks.",
  text_39: "Enviam para todo o Brasil?",
  text_40: "Sim! Enviamos as nossas coleções para todo o território nacional. Basta entrar em contacto pelo WhatsApp para simularmos o prazo de entrega e o valor do frete para a sua morada. 📦",
  text_41: "Qual o foco da coleção Boreal?",
  text_42: "A Coleção Boreal traduz a intensidade das cores num encontro inusitado. Trazemos peças-chave, modelagens sofisticadas e cores que transitam perfeitamente do dia para a noite.",
  text_43: "© 2026 ZISA LOJA",
  text_44: "Criado por",
  text_45: "VERTICY.",
  text_46: "Premium Bio",
};
